#!/bin/bash
nohup php app/console bench:split:generateData --split6=true --startNb=1 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=1001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=1201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=1401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=1601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=1801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=2001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=2201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=2401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=2601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=2801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=3001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=3201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=3401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=3601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=3801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=4001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=4201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=4401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=4601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=4801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=5001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=5201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=5401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=5601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=5801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=6001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=6201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=6401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=6601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=6801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=7001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=7201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=7401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=7601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=7801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=8001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=8201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=8401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=8601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=8801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=9001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=9201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=9401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=9601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=9801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=10001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=10201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=10401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=10601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=10801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=11001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=11201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=11401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=11601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=11801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=12001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=12201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=12401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=12601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=12801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=13001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=13201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=13401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=13601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=13801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=14001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=14201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=14401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=14601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=14801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=15001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=15201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=15401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=15601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=15801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=16001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=16201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=16401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=16601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=16801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=17001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=17201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=17401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=17601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=17801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=18001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=18201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=18401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=18601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=18801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=19001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=19201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=19401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=19601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=19801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=20001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=20201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=20401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=20601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=20801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=21001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=21201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=21401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=21601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=21801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=22001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=22201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=22401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=22601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=22801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=23001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=23201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=23401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=23601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=23801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=24001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=24201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=24401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=24601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=24801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=25001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=25201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=25401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=25601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=25801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=26001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=26201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=26401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=26601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=26801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=27001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=27201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=27401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=27601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=27801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=28001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=28201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=28401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=28601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=28801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=29001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=29201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=29401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=29601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=29801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=30001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=30201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=30401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=30601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=30801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=31001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=31201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=31401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=31601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=31801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=32001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=32201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=32401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=32601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=32801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=33001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=33201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=33401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=33601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=33801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=34001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=34201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=34401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=34601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=34801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=35001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=35201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=35401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=35601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=35801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=36001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=36201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=36401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=36601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=36801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=37001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=37201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=37401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=37601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=37801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=38001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=38201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=38401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=38601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=38801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=39001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=39201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=39401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=39601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=39801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=40001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=40201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=40401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=40601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=40801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=41001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=41201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=41401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=41601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=41801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=42001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=42201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=42401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=42601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=42801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=43001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=43201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=43401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=43601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=43801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=44001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=44201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=44401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=44601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=44801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=45001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=45201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=45401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=45601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=45801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=46001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=46201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=46401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=46601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=46801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=47001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=47201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=47401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=47601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=47801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=48001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=48201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=48401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=48601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=48801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=49001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=49201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=49401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=49601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=49801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=50001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=50201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=50401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=50601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=50801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=51001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=51201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=51401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=51601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=51801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=52001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=52201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=52401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=52601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=52801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=53001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=53201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=53401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=53601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=53801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=54001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=54201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=54401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=54601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=54801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=55001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=55201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=55401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=55601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=55801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=56001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=56201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=56401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=56601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=56801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=57001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=57201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=57401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=57601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=57801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=58001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=58201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=58401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=58601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=58801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=59001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=59201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=59401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=59601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=59801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=60001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=60201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=60401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=60601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=60801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=61001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=61201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=61401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=61601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=61801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=62001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=62201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=62401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=62601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=62801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=63001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=63201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=63401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=63601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=63801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=64001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=64201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=64401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=64601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=64801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=65001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=65201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=65401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=65601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=65801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=66001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=66201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=66401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=66601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=66801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=67001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=67201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=67401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=67601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=67801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=68001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=68201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=68401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=68601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=68801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=69001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=69201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=69401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=69601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=69801 > /dev/null &
