#!/bin/bash
nohup php app/console bench:split:generateData --split6=true --startNb=1 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=1001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=1201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=1401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=1601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=1801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=2001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=2201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=2401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=2601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=2801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=3001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=3201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=3401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=3601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=3801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=4001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=4201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=4401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=4601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=4801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=5001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=5201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=5401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=5601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=5801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=6001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=6201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=6401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=6601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=6801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=7001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=7201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=7401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=7601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=7801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=8001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=8201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=8401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=8601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=8801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=9001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=9201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=9401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=9601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=9801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=10001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=10201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=10401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=10601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=10801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=11001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=11201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=11401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=11601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=11801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=12001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=12201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=12401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=12601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=12801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=13001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=13201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=13401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=13601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=13801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=14001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=14201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=14401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=14601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=14801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=15001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=15201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=15401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=15601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=15801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=16001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=16201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=16401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=16601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=16801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=17001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=17201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=17401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=17601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=17801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=18001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=18201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=18401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=18601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=18801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=19001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=19201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=19401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=19601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=19801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=20001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=20201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=20401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=20601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=20801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=21001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=21201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=21401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=21601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=21801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=22001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=22201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=22401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=22601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=22801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=23001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=23201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=23401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=23601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=23801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=24001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=24201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=24401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=24601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=24801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=25001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=25201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=25401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=25601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=25801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=26001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=26201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=26401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=26601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=26801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=27001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=27201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=27401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=27601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=27801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=28001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=28201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=28401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=28601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=28801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=29001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=29201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=29401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=29601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=29801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=30001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=30201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=30401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=30601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=30801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=31001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=31201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=31401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=31601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=31801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=32001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=32201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=32401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=32601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=32801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=33001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=33201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=33401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=33601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=33801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=34001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=34201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=34401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=34601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=34801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=35001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=35201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=35401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=35601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=35801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=36001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=36201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=36401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=36601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=36801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=37001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=37201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=37401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=37601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=37801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=38001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=38201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=38401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=38601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=38801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=39001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=39201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=39401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=39601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=39801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=40001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=40201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=40401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=40601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=40801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=41001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=41201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=41401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=41601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=41801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=42001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=42201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=42401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=42601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=42801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=43001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=43201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=43401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=43601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=43801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=44001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=44201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=44401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=44601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=44801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=45001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=45201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=45401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=45601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=45801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=46001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=46201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=46401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=46601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=46801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=47001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=47201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=47401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=47601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=47801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=48001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=48201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=48401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=48601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=48801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=49001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=49201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=49401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=49601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=49801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=50001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=50201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=50401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=50601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=50801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=51001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=51201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=51401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=51601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=51801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=52001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=52201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=52401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=52601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=52801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=53001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=53201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=53401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=53601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=53801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=54001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=54201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=54401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=54601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=54801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=55001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=55201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=55401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=55601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=55801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=56001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=56201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=56401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=56601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=56801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=57001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=57201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=57401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=57601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=57801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=58001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=58201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=58401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=58601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=58801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=59001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=59201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=59401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=59601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=59801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=60001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=60201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=60401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=60601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=60801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=61001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=61201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=61401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=61601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=61801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=62001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=62201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=62401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=62601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=62801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=63001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=63201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=63401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=63601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=63801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=64001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=64201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=64401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=64601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=64801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=65001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=65201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=65401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=65601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=65801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=66001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=66201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=66401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=66601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=66801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=67001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=67201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=67401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=67601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=67801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=68001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=68201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=68401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=68601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=68801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=69001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=69201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=69401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=69601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=69801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=70001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=70201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=70401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=70601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=70801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=71001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=71201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=71401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=71601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=71801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=72001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=72201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=72401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=72601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=72801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=73001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=73201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=73401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=73601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=73801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=74001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=74201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=74401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=74601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=74801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=75001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=75201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=75401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=75601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=75801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=76001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=76201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=76401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=76601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=76801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=77001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=77201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=77401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=77601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=77801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=78001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=78201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=78401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=78601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=78801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=79001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=79201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=79401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=79601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=79801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=80001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=80201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=80401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=80601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=80801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=81001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=81201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=81401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=81601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=81801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=82001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=82201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=82401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=82601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=82801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=83001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=83201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=83401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=83601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=83801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=84001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=84201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=84401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=84601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=84801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=85001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=85201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=85401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=85601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=85801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=86001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=86201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=86401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=86601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=86801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=87001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=87201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=87401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=87601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=87801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=88001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=88201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=88401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=88601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=88801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=89001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=89201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=89401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=89601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=89801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=90001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=90201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=90401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=90601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=90801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=91001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=91201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=91401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=91601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=91801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=92001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=92201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=92401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=92601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=92801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=93001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=93201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=93401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=93601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=93801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=94001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=94201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=94401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=94601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=94801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=95001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=95201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=95401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=95601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=95801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=96001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=96201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=96401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=96601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=96801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=97001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=97201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=97401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=97601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=97801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=98001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=98201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=98401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=98601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=98801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=99001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=99201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=99401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=99601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=99801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=100001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=100201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=100401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=100601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=100801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=101001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=101201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=101401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=101601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=101801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=102001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=102201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=102401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=102601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=102801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=103001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=103201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=103401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=103601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=103801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=104001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=104201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=104401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=104601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=104801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=105001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=105201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=105401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=105601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=105801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=106001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=106201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=106401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=106601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=106801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=107001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=107201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=107401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=107601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=107801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=108001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=108201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=108401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=108601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=108801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=109001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=109201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=109401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=109601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=109801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=110001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=110201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=110401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=110601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=110801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=111001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=111201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=111401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=111601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=111801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=112001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=112201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=112401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=112601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=112801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=113001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=113201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=113401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=113601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=113801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=114001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=114201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=114401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=114601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=114801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=115001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=115201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=115401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=115601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=115801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=116001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=116201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=116401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=116601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=116801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=117001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=117201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=117401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=117601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=117801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=118001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=118201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=118401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=118601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=118801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=119001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=119201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=119401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=119601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=119801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=120001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=120201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=120401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=120601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=120801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=121001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=121201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=121401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=121601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=121801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=122001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=122201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=122401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=122601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=122801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=123001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=123201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=123401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=123601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=123801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=124001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=124201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=124401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=124601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=124801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=125001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=125201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=125401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=125601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=125801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=126001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=126201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=126401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=126601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=126801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=127001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=127201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=127401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=127601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=127801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=128001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=128201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=128401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=128601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=128801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=129001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=129201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=129401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=129601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=129801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=130001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=130201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=130401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=130601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=130801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=131001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=131201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=131401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=131601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=131801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=132001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=132201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=132401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=132601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=132801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=133001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=133201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=133401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=133601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=133801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=134001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=134201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=134401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=134601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=134801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=135001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=135201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=135401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=135601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=135801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=136001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=136201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=136401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=136601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=136801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=137001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=137201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=137401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=137601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=137801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=138001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=138201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=138401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=138601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=138801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=139001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=139201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=139401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=139601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=139801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=140001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=140201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=140401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=140601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=140801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=141001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=141201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=141401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=141601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=141801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=142001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=142201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=142401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=142601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=142801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=143001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=143201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=143401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=143601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=143801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=144001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=144201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=144401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=144601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=144801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=145001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=145201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=145401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=145601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=145801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=146001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=146201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=146401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=146601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=146801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=147001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=147201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=147401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=147601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=147801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=148001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=148201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=148401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=148601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=148801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=149001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=149201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=149401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=149601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=149801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=150001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=150201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=150401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=150601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=150801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=151001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=151201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=151401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=151601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=151801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=152001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=152201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=152401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=152601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=152801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=153001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=153201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=153401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=153601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=153801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=154001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=154201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=154401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=154601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=154801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=155001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=155201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=155401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=155601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=155801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=156001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=156201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=156401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=156601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=156801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=157001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=157201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=157401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=157601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=157801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=158001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=158201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=158401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=158601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=158801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=159001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=159201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=159401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=159601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=159801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=160001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=160201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=160401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=160601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=160801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=161001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=161201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=161401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=161601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=161801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=162001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=162201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=162401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=162601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=162801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=163001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=163201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=163401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=163601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=163801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=164001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=164201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=164401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=164601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=164801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=165001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=165201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=165401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=165601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=165801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=166001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=166201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=166401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=166601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=166801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=167001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=167201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=167401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=167601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=167801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=168001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=168201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=168401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=168601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=168801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=169001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=169201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=169401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=169601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=169801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=170001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=170201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=170401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=170601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=170801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=171001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=171201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=171401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=171601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=171801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=172001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=172201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=172401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=172601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=172801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=173001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=173201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=173401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=173601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=173801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=174001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=174201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=174401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=174601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=174801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=175001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=175201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=175401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=175601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=175801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=176001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=176201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=176401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=176601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=176801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=177001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=177201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=177401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=177601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=177801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=178001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=178201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=178401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=178601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=178801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=179001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=179201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=179401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=179601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=179801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=180001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=180201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=180401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=180601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=180801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=181001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=181201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=181401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=181601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=181801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=182001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=182201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=182401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=182601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=182801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=183001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=183201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=183401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=183601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=183801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=184001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=184201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=184401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=184601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=184801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=185001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=185201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=185401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=185601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=185801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=186001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=186201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=186401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=186601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=186801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=187001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=187201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=187401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=187601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=187801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=188001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=188201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=188401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=188601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=188801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=189001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=189201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=189401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=189601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=189801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=190001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=190201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=190401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=190601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=190801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=191001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=191201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=191401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=191601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=191801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=192001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=192201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=192401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=192601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=192801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=193001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=193201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=193401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=193601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=193801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=194001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=194201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=194401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=194601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=194801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=195001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=195201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=195401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=195601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=195801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=196001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=196201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=196401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=196601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=196801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=197001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=197201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=197401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=197601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=197801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=198001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=198201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=198401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=198601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=198801 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=199001 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=199201 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=199401 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=199601 > /dev/null &
nohup php app/console bench:split:generateData --split6=true --startNb=199801 > /dev/null &
