sm_split_collection:
    resource: "@SMSplitCollectionBundle/Controller/"
    type:     annotation
    prefix:   /

sm_bucket_poke:
    resource: "@SMBucketPokeBundle/Controller/"
    type:     annotation
    prefix:   /

sm_poke_embed:
    resource: "@SMPokeEmbedBundle/Controller/"
    type:     annotation
    prefix:   /

sm_goals_agreg:
    resource: "@SMGoalsAgregBundle/Controller/"
    type:     annotation
    prefix:   /

sm_flat_ad_stat:
    resource: "@SMFlatAdStatBundle/Controller/"
    type:     annotation
    prefix:   /

sm_bench:
    resource: "@SMBenchBundle/Controller/"
    type:     annotation
    prefix:   /

# Internal routing configuration to handle ESI
# ****** WARNING ******
# This route should be enabled with caution as it can open a security vulnerability
# see http://symfony.com/blog/security-release-symfony-2-0-20-and-2-1-5-released for more information
# ****** WARNING ******
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
